//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.CompanyCommunicator.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.CompanyCommunicator.Common.Resources.Strings - Copy", typeof(Strings___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact your IT admin for permission to view this data..
        /// </summary>
        public static string AdminConsentError {
            get {
                return ResourceManager.GetString("AdminConsentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Not Installed.
        /// </summary>
        public static string AppNotInstalled {
            get {
                return ResourceManager.GetString("AppNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Status.
        /// </summary>
        public static string ColumnName_DeliveryStatus {
            get {
                return ResourceManager.GetString("ColumnName_DeliveryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ColumnName_Error {
            get {
                return ResourceManager.GetString("ColumnName_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported By.
        /// </summary>
        public static string ColumnName_ExportedBy {
            get {
                return ResourceManager.GetString("ColumnName_ExportedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export TimeStamp.
        /// </summary>
        public static string ColumnName_ExportTimeStamp {
            get {
                return ResourceManager.GetString("ColumnName_ExportTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Title.
        /// </summary>
        public static string ColumnName_MessageTitle {
            get {
                return ResourceManager.GetString("ColumnName_MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent TimeStamp.
        /// </summary>
        public static string ColumnName_SentTimeStamp {
            get {
                return ResourceManager.GetString("ColumnName_SentTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Reason.
        /// </summary>
        public static string ColumnName_StatusReason {
            get {
                return ResourceManager.GetString("ColumnName_StatusReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team ID.
        /// </summary>
        public static string ColumnName_TeamId {
            get {
                return ResourceManager.GetString("ColumnName_TeamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Name.
        /// </summary>
        public static string ColumnName_TeamName {
            get {
                return ResourceManager.GetString("ColumnName_TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPN.
        /// </summary>
        public static string ColumnName_Upn {
            get {
                return ResourceManager.GetString("ColumnName_Upn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string ColumnName_UserId {
            get {
                return ResourceManager.GetString("ColumnName_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ColumnName_UserName {
            get {
                return ResourceManager.GetString("ColumnName_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        public static string ColumnName_UserType {
            get {
                return ResourceManager.GetString("ColumnName_UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (copy).
        /// </summary>
        public static string DuplicateText {
            get {
                return ResourceManager.GetString("DuplicateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Try exporting the results again..
        /// </summary>
        public static string ExportFailureText {
            get {
                return ResourceManager.GetString("ExportFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create conversation. Error message: {0}.
        /// </summary>
        public static string FailedToCreateConversationFormat {
            get {
                return ResourceManager.GetString("FailedToCreateConversationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create conversation with teams user: {0}. Exception: {1}.
        /// </summary>
        public static string FailedToCreateConversationForUserFormat {
            get {
                return ResourceManager.GetString("FailedToCreateConversationForUserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create conversation. Request throttled. Error message: {0}&quot;.
        /// </summary>
        public static string FailedToCreateConversationThrottledFormt {
            get {
                return ResourceManager.GetString("FailedToCreateConversationThrottledFormt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the team {0} in DB..
        /// </summary>
        public static string FailedToFindTeamInDbFormat {
            get {
                return ResourceManager.GetString("FailedToFindTeamInDbFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the User application: {0} in the organization&apos;s app catalog..
        /// </summary>
        public static string FailedToFindUserAppInAppCatalog {
            get {
                return ResourceManager.GetString("FailedToFindUserAppInAppCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sync all users. Status Code: {0} Exception: {1}.
        /// </summary>
        public static string FailedToGetAllUsersFormat {
            get {
                return ResourceManager.GetString("FailedToGetAllUsersFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get conversation id for user: {0}. Status Code: {1} Exception: {2}.
        /// </summary>
        public static string FailedToGetConversationForUserFormat {
            get {
                return ResourceManager.GetString("FailedToGetConversationForUserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get members for group {0}: {1}.
        /// </summary>
        public static string FailedToGetMembersForGroupFormat {
            get {
                return ResourceManager.GetString("FailedToGetMembersForGroupFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get members for team {0}: {1}.
        /// </summary>
        public static string FailedToGetMembersForTeamFormat {
            get {
                return ResourceManager.GetString("FailedToGetMembersForTeamFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install application for user: {0}. Exception: {1}.
        /// </summary>
        public static string FailedToInstallApplicationForUserFormat {
            get {
                return ResourceManager.GetString("FailedToInstallApplicationForUserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to prepare the message for sending:{0}.
        /// </summary>
        public static string FailtoPrepareMessageFormat {
            get {
                return ResourceManager.GetString("FailtoPrepareMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file contains the results you exported..
        /// </summary>
        public static string FileCardDescription {
            get {
                return ResourceManager.GetString("FileCardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link for this download has expired. Export the results again..
        /// </summary>
        public static string FileCardExpireText {
            get {
                return ResourceManager.GetString("FileCardExpireText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportData.
        /// </summary>
        public static string FileName_ExportData {
            get {
                return ResourceManager.GetString("FileName_ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message_Delivery.
        /// </summary>
        public static string FileName_Message_Delivery {
            get {
                return ResourceManager.GetString("FileName_Message_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string FileName_Metadata {
            get {
                return ResourceManager.GetString("FileName_Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file is ready to download. A copy is also available in OneDrive..
        /// </summary>
        public static string FileReadyText {
            get {
                return ResourceManager.GetString("FileReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Try exporting the results again..
        /// </summary>
        public static string FileUploadErrorText {
            get {
                return ResourceManager.GetString("FileUploadErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest User not supported.
        /// </summary>
        public static string GuestUserNotSupported {
            get {
                return ResourceManager.GetString("GuestUserNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        public static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification has {0} groups as its recipients. It shouldn&apos;t exceed {1} groups..
        /// </summary>
        public static string NumberOfGroupsExceededLimitWarningFormat {
            get {
                return ResourceManager.GetString("NumberOfGroupsExceededLimitWarningFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification has {0} rosters as its recipients. It shouldn&apos;t exceed {1} rosters..
        /// </summary>
        public static string NumberOfRostersExceededLimitWarningFormat {
            get {
                return ResourceManager.GetString("NumberOfRostersExceededLimitWarningFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notification has {0} teams as its recipients. It shouldn&apos;t exceed {1} teams..
        /// </summary>
        public static string NumberOfTeamsExceededLimitWarningFormat {
            get {
                return ResourceManager.GetString("NumberOfTeamsExceededLimitWarningFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission declined. We will not proceed with the export..
        /// </summary>
        public static string PermissionDeclinedText {
            get {
                return ResourceManager.GetString("PermissionDeclinedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient Not Found.
        /// </summary>
        public static string RecipientNotFound {
            get {
                return ResourceManager.GetString("RecipientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded.
        /// </summary>
        public static string Succeeded {
            get {
                return ResourceManager.GetString("Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throttled.
        /// </summary>
        public static string Throttled {
            get {
                return ResourceManager.GetString("Throttled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User application not found. Make sure the User app is uploaded to your organization&apos;s app catalog..
        /// </summary>
        public static string UserAppNotFound {
            get {
                return ResourceManager.GetString("UserAppNotFound", resourceCulture);
            }
        }
    }
}
